# Generated by Django 5.1.6 on 2025-03-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_fix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='appointment_role_91b7c3_idx',
            old_name='user_role_idx',
        ),
    ]
