# Generated by Django 5.1.6 on 2025-03-01 19:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_user_role_idx_appointment_role_91b7c3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('20.00'))]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='No qualification', max_length=100),
        ),
    ]
