# Generated by Django 5.1.7 on 2025-04-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_allergies_appointment_blood_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, help_text="Patient's contact phone for this appointment", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='booking_history',
            field=models.TextField(blank=True, help_text='History of bookings', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='daily_patient_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of patients per day'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_available',
            field=models.BooleanField(default=False, help_text='Available for emergency response'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Currently accepting appointments'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='List any chronic diseases the patient has', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='past_examinations',
            field=models.TextField(blank=True, help_text='List of past medical examinations', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_patients', to='appointments.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='appointments.medicalcenter'),
        ),
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('examination_type', models.CharField(max_length=100)),
                ('results', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_examinations', to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_examinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
